version: "3.9"
services:
  postgres:
    container_name: databackend-db
    image: postgres:latest
    environment:
      POSTGRES_DB: databackend
      POSTGRES_USER: databackend
      POSTGRES_PASSWORD: databackend
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U databackend']
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - databackend-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend
    restart: unless-stopped

  analytics:
    container_name: analytics-db
    image: postgres:latest
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U databackend']
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - analytics-db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - backend
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - databackend-pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:

volumes:
  databackend-db:
  databackend-pgadmin: